# Learn more at https://maxkostinevich.com/blog/deploy-jigsaw-using-github-actions

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install NPM Dependencies
      run: npm install
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Build website
      run: npm run production
    - name: Prepare production
      run: |
        git config --global user.email "borisdehoumon@gmail.com"
        git config --global user.name "Boris DEHOUMON"
        git add build_production -f && git commit -m "Build for deploy support"
    - name: Pushes to support repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.DEPLOY_KEY }}
      with:
        source-directory: 'build_production'
        destination-github-username: 'dehboris'
        destination-repository-name: 'support-dev-mobile'
        user-email: borisdehoumon@gmail.com
  
